# Generated by Django 4.0.5 on 2022-06-23 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(choices=[('last_attack_heat_2022', 'Last Attack Heat 2022')], default='last_attack_heat_2022', max_length=200, verbose_name='Соревнование')),
                ('fio', models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Фамилия Имя')),
                ('phone', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Контактный телефон')),
                ('number', models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Стартовый номер участника')),
                ('klass', models.CharField(choices=[('lite', 'Лайт'), ('hobby', 'Хобби'), ('expert', 'Эксперт')], max_length=20, verbose_name='Класс участия')),
                ('city', models.CharField(blank=True, default='', max_length=200, verbose_name='Город')),
                ('team', models.CharField(blank=True, default='', max_length=200, verbose_name='Комманда')),
                ('bike', models.CharField(blank=True, default='', max_length=200, verbose_name='Модель мотоцикла')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
    ]
